# Generated by Django 5.1 on 2024-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_user',
            field=models.IntegerField(default=5),
        ),
    ]
