# Generated by Django 5.1 on 2024-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_user',
            field=models.IntegerField(),
        ),
    ]
