# Generated by Django 5.1 on 2024-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierole',
            name='is_cast',
            field=models.BooleanField(default=True),
        ),
    ]
