# Generated by Django 5.1 on 2024-09-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0002_movierole_is_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_key',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
