# Generated by Django 5.1 on 2024-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0003_alter_movie_video_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
