# Generated by Django 5.1 on 2024-10-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0005_alter_movie_description_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, default='No description available.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
