# Generated by Django 5.1 on 2024-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0007_hashtag_review_reviewreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
