# Generated by Django 5.1 on 2024-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreaction',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7, null=True),
        ),
    ]
