# Generated by Django 5.1 on 2024-11-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0013_alter_reviewreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7),
        ),
    ]
