# Generated by Django 5.1 on 2024-11-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0014_alter_reviewreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
