# Generated by Django 5.1 on 2024-12-18 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_management', '0015_alter_review_rating'),
        ('theater_managemant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='movie_management.movie')),
            ],
        ),
        migrations.CreateModel(
            name='DailyShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_shows', to='screen_management.movieschedule')),
            ],
            options={
                'unique_together': {('schedule', 'show_date', 'show_time')},
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=None)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theater_managemant.screen')),
            ],
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='screen_management.showtime'),
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('reserved', 'Reserved'), ('available', 'Available')], default='available', max_length=10)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('seat_row', models.CharField(max_length=5)),
                ('seat_column', models.PositiveIntegerField()),
                ('tier_row', models.IntegerField()),
                ('tier_column', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=5, null=True)),
                ('tier_name', models.CharField(max_length=50)),
                ('tier_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.IntegerField(default=0)),
                ('daily_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='screen_management.dailyshow')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='theater_managemant.seat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('daily_show', 'seat')},
            },
        ),
    ]
