# Generated by Django 5.1 on 2024-11-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_identifier', models.CharField(max_length=10)),
                ('seat_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('theater_name', models.TextField()),
                ('screen_name', models.CharField()),
                ('theater_address', models.TextField()),
                ('booking_id', models.CharField(max_length=150, null=True)),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('movie_title', models.CharField(max_length=150)),
                ('movie_poster', models.URLField(blank=True, max_length=500, null=True)),
                ('movie_backdrop', models.URLField(blank=True, max_length=500, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('is_snacks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('image_url', models.URLField()),
                ('price', models.CharField(max_length=10)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_snacks', to='booking_management.booking')),
            ],
        ),
    ]
