# Generated by Django 5.1 on 2024-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0002_bookedticket_tier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='tier_name',
            field=models.CharField(max_length=100),
        ),
    ]
