# Generated by Django 5.1 on 2024-11-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0003_alter_bookedticket_tier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedticket',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking_management.booking'),
        ),
    ]
