# Generated by Django 5.1 on 2024-11-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0005_alter_bookedticket_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersnack',
            name='snack_id',
            field=models.IntegerField(default=0),
        ),
    ]
