# Generated by Django 5.1 on 2024-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0006_ordersnack_snack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordersnack',
            name='snack_id',
            field=models.IntegerField(),
        ),
    ]
