# Generated by Django 5.1 on 2024-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0007_booking_qr_code_alter_ordersnack_snack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
