# Generated by Django 5.1 on 2024-11-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0008_booking_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ticket', to='booking_management.booking'),
        ),
        migrations.AlterField(
            model_name='ordersnack',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_snack', to='booking_management.booking'),
        ),
    ]
