# Generated by Django 5.1 on 2024-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0011_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='screen_id',
            field=models.BigIntegerField(default=54),
        ),
        migrations.AddField(
            model_name='booking',
            name='theater_id',
            field=models.BigIntegerField(default=13),
        ),
    ]
