# Generated by Django 5.1 on 2024-12-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0012_booking_screen_id_booking_theater_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='screen_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater_id',
            field=models.BigIntegerField(),
        ),
    ]
